### ISSUE TITLE
Zippey Circuit diagram

### ISSUE THREAD

**Issue by BRoy98** [elkayem/ZippyTheBalancingRobot#1]
I just saw the video and Zippy is very stable and working awesome. I am planning to make one like this! Please provide a circuit diagram of Zippy also. So excited about this. Thanks in advance.

**Comment by elkayem** [comment]
I'm glad you like the video and the design!  I wired it together on the fly, so never actually wrote down the schematic.  I get a lot of requests for the schematic, and so have been considering putting one together for quite some time.  Perhaps I'll even have a custom board manufactured for this!  I'll take your note as a challenge to put together a schematic.  I may not get around to it for a while (a few months?) but can definitely answer questions.

**Comment by elkayem** [comment]
Ok, I finally broke down and put together a schematic in Eagle.  Look in the Eagle folder.  Closing this issue.
